# tombi: format.rules.table-keys-order = "version-sort"

fix = true
line-length = 120  # Allow lines to be as long as 120.
target-version = "py314"  # Always generate Python 3.14-compatible code.

[format]
docstring-code-format = true  # Enable reformatting of code snippets in docstrings.
skip-magic-trailing-comma = true
