# tombi: format.rules.table-keys-order = "version-sort"
#:tombi schema.strict = false

[formatting]
align_comments = false
align_entries = false
allowed_blank_lines = 1
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
column_width = 120
compact_arrays = false
compact_entries = false
compact_inline_tables = false
crlf = false
indent_entries = false
indent_tables = false
inline_table_expand = true
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true
trailing_newline = true
