[formatting]
align_comments = false # Align consecutive comments after entries and items vertically. This applies to comments that are after entries or array items.
allowed_blank_lines = 1 # The maximum amount of consecutive blank lines allowed.
compact_arrays = false
reorder_arrays = true
reorder_inline_tables = true
reorder_keys = true
